version: "3"

services:
  app:
    build:
      context: ""

    ports:
      - "8000:8000"
    
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    
    restart: always

    command: >
      sh -c "
        python load/load_csv.py
      "

    volumes:
      - .:/app
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      
    depends_on:
      - postgresdb
      
    networks:
      - monreseau    
    links:
      - postgresdb

  postgresdb:

    image: postgres:14.1-alpine

    networks:
      - monreseau    

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  


  admine:

    image: adminer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    networks:
      - monreseau    
    links:
      - postgresdb

networks:
  monreseau:
     name: monreseau